import { rawSchemaToDiscovery, type RawForeignKey, type RawSchema, type RawTable } from './raw-schema.js';
import type { DataModelDiscovery } from '../types.js';

/**
 * Parse Rails `db/schema.rb`. The file is machine-generated by Rails'
 * schema dumper and line-regular, so a structured line parser is reliable —
 * this is the same call Liam ERD and dbdiagram make, minus their parser
 * dependencies. Handles:
 *   create_table "users" ... do |t| ... end
 *   t.string "name"            (column)
 *   t.references "org" / t.belongs_to "org"   (org_id column + FK intent)
 *   t.index ["email"], unique: true
 *   add_foreign_key "posts", "users"[, column: "author_id"]
 */
export function parseSchemaRb(filePath: string, content: string): DataModelDiscovery | null {
  const tables = new Map<string, RawTable>();
  const foreignKeys: RawForeignKey[] = [];
  let current: RawTable | null = null;

  const COLUMN_TYPES = new Set([
    'string', 'text', 'integer', 'bigint', 'float', 'decimal', 'numeric', 'datetime', 'time',
    'date', 'binary', 'boolean', 'json', 'jsonb', 'uuid', 'citext', 'inet', 'interval', 'virtual',
  ]);

  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim();

    const createMatch = line.match(/^create_table\s+"([^"]+)"/);
    if (createMatch) {
      current = {
        name: createMatch[1],
        filePath,
        columns: [],
        // Rails defaults to a bigint `id` primary key unless `id: false`
        pkColumns: /id:\s*false/.test(line) ? [] : ['id'],
      };
      if (!/id:\s*false/.test(line)) current.columns.push({ name: 'id' });
      tables.set(current.name, current);
      continue;
    }

    if (line === 'end') {
      current = null;
      continue;
    }

    if (current) {
      const colMatch = line.match(/^t\.(\w+)\s+"([^"]+)"/);
      if (colMatch && COLUMN_TYPES.has(colMatch[1])) {
        current.columns.push({ name: colMatch[2] });
        continue;
      }

      // t.references "org" / t.belongs_to :org → org_id column, FK to orgs
      const refMatch = line.match(/^t\.(?:references|belongs_to)\s+(?:"([^"]+)"|:(\w+))/);
      if (refMatch) {
        const refName = refMatch[1] ?? refMatch[2];
        const columnName = `${refName}_id`;
        current.columns.push({ name: columnName });
        // The dumper emits add_foreign_key lines for real FKs; only register
        // from t.references when an inline `foreign_key: true` is present, to
        // avoid double counting (the dedupe in rawSchemaToDiscovery also guards).
        if (/foreign_key:\s*true/.test(line)) {
          foreignKeys.push({
            fromTable: current.name,
            fromColumns: [columnName],
            toTable: pluralize(refName),
            toColumns: ['id'],
          });
        }
        continue;
      }

      const indexMatch = line.match(/^t\.index\s+\[([^\]]+)\].*unique:\s*true/);
      if (indexMatch) {
        const cols = [...indexMatch[1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);
        if (cols.length === 1) {
          const column = current.columns.find((c) => c.name === cols[0]);
          if (column) column.unique = true;
        }
        continue;
      }
    }

    const fkMatch = line.match(/^add_foreign_key\s+"([^"]+)",\s+"([^"]+)"(.*)$/);
    if (fkMatch) {
      const [, fromTable, toTable, rest] = fkMatch;
      const columnMatch = rest.match(/column:\s*"([^"]+)"/);
      const fromColumn = columnMatch ? columnMatch[1] : `${singularize(toTable)}_id`;
      foreignKeys.push({ fromTable, fromColumns: [fromColumn], toTable, toColumns: ['id'] });
    }
  }

  if (tables.size === 0) return null;
  const raw: RawSchema = { source: 'rails', tables: [...tables.values()], foreignKeys };
  return rawSchemaToDiscovery(raw);
}

/** Just enough inflection for Rails FK conventions (users → user_id) */
function singularize(name: string): string {
  if (name.endsWith('ies')) return name.slice(0, -3) + 'y';
  if (name.endsWith('ses') || name.endsWith('xes') || name.endsWith('zes')) return name.slice(0, -2);
  if (name.endsWith('s') && !name.endsWith('ss')) return name.slice(0, -1);
  return name;
}

function pluralize(name: string): string {
  if (name.endsWith('y') && !/[aeiou]y$/.test(name)) return name.slice(0, -1) + 'ies';
  if (name.endsWith('s') || name.endsWith('x') || name.endsWith('z')) return name + 'es';
  return name + 's';
}
